### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by ecrystale** [lli15/miesesOpening#3]
The user interaction seems pretty clear, which is by choosing axes, and then generation and/or type - can more than one be chosen or none at all? However, how would you chose which stat distribution to show? Is it the average of all the data? This data would be compelling for people interested in Pokemon and want a way to compare Pokemon quickly. The interaction does encourage users to explore as there are many different combinations that can be picked.

**Comment by jason-tung** [comment]
Could you clarify your questions?
