### ISSUE TITLE
rev_A by cerealKillers

### ISSUE THREAD

**Issue by tfabiha** [lli15/miesesOpening#4]
The visualization of this data would be more useful while playing pokemon if you were able to compare individual pokemon rather than more broad groups, especially if you're using it as most players do, to prepare competitive teams. Being able to compare just say the hp of all pokemon to their speed doesn't necessarily give us any valuable information. But if we were able to compare the full stats of any two pokemon at a time, maybe with the second graph you've depicted in your README, the user would receive much more useful information.

P.S. Press F for Game Phreak.
P.P.S. Fire type pokemon are mainly special attackers, not physical attackers.

**Comment by rachel-ng** [comment]
F

**Comment by jason-tung** [comment]
I don't know if it's in the readme, but you'll be able to filter by name/number, so that you can compare stats for just two pokemon if you provide their names.
